variable "broker_username" {}
variable "broker_password" {}
variable "docker_image_tag" {}
variable "docker_registry_url" {}
variable "flower_basic_auth" {}
variable "github_organization" {}
variable "github_token" {}
variable "include_dag_examples" {}
variable "kubernetes_api_server_endpoint" {}
variable "kubernetes_api_server_cert_auth" {}
variable "mysql_username" {}
variable "mysql_password" {}
variable "provider_access_key" {}
variable "provider_secret_key" {}
variable "ssl_cert_arn" {}
variable "vpc_id" {}